version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - nextcloud_db:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=password

  redis:
    image: redis:7.2-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: .env

  app:
    image: nextcloud:29-apache
    container_name: nextcloud-app
    restart: unless-stopped
    ports:
      - "8095:80"
    volumes:
      - nextcloud_app:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    env_file: .env
    depends_on:
      - db
      - redis

volumes:
  nextcloud_db:
  nextcloud_app:
