version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8086:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - core
    restart: unless-stopped

networks:
  core:
    external: true

volumes:
  pgadmin_data:
