version: "3.8"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    env_file:
      - ../../.env # Points to the .env file in the homelab root
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - ~/homelab:/config/workspace/homelab
    ports:
      - "8443:8443"
    restart: unless-stopped
