version: "3.8"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3333:3000"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Kolkata
      # Corrected list including host:port for both local and Tailscale IPs
      HOMEPAGE_ALLOWED_HOSTS: "192.168.29.50,192.168.29.50:3333,100.65.94.2,100.65.94.2:3333,localhost,127.0.0.1"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
