services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    networks: [core]
    env_file:
      - ./.env
    ports:
      - "5432:5432"   # local dev access if needed
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
    external: false
networks:
  core:
    external: true
