global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Glances exposes a Prometheus endpoint on 61209
  - job_name: 'glances'
    metrics_path: /metrics
    static_configs:
      - targets: ['glances:61209']

  # Uptime via Blackbox (HTTP 200/302 allowed)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://home.msi.local
        - https://grafana.msi.local
        - https://prom.msi.local
        - https://portainer.msi.local
        - https://next.msi.local
        - https://n8n.msi.local
        - https://nocodb.msi.local
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
