version: "3.8"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      # Bind ONLY to the LAN IP to avoid conflict with systemd-resolved on 127.0.0.53
      - "192.168.29.50:53:53/tcp"
      - "192.168.29.50:53:53/udp"
      - "192.168.29.50:3000:3000/tcp"  # installer
      - "192.168.29.50:8080:80/tcp"    # dashboard
      # Optional (enable later):
      # - "192.168.29.50:853:853/tcp"    # DoT
      # - "192.168.29.50:5443:5443/tcp"  # DoH
    volumes:
      - ./data:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf
    networks:
      - core

networks:
  core:
    external: true
