services:
  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    restart: unless-stopped
    networks: [core]
    volumes:
      - ./blackbox.yml:/config/blackbox.yml:ro
    command:
      - --config.file=/config/blackbox.yml

networks:
  core:
    external: true
