version: '3.8'

services:
  gitea:
    image: gitea/gitea:1.21.7
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Asia/Kolkata
    networks:
      - core
    volumes:
      - gitea_data:/data
    ports:
      - "3004:3000"
      - "2222:22"
    restart: unless-stopped

networks:
  core:
    external: true

volumes:
  gitea_data:
